name: Build Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2.12.0
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup signing files
      run: |
        echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties
        
    - name: Decode Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'kwindowcalculator.jks'
        fileDir: './android/app/'
        encodedString: ${{ secrets.KEYSTORE_FILE_ANDROID }}
        
    - name: Build App Bundle
      run: flutter build appbundle --release --build-number=${GITHUB_RUN_NUMBER}
      
    - name: Upload a generated artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: release-aab
        path: build/app/outputs/bundle/release/app-release.aab
          
