name: Build Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2.12.0
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build App Bundle
      run: flutter build appbundle --release --build-number=${GITHUB_RUN_NUMBER}

    - uses: ilharp/sign-android-release@v1
      name: Sign app APK
      # ID used to access action output
      id: sign_app
      with:
        releaseDir: build/app/outputs/bundle/release
        signingKey: ${{ secrets.KEYSTORE_FILE_ANDROID }}
        keyAlias: kWindowCalculator
        keyStorePassword: ${{ secrets.KEY_STORE_GPG_PASSWORD }}
        keyPassword: ${{ secrets.KEY_STORE_GPG_PASSWORD }}
        buildToolsVersion: 33.0.0
      
    - name: Upload a generated artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: release-aab
        path: build/app/outputs/bundle/release/app-release.aab
          
